apiVersion: v1
kind: Pod
metadata:
  name: "members-service"
  namespace: default
  labels:
    app: members-service
spec:
  containers:
  - name: members-service
    image: "pusti/rso2324-team22-members-service:0.0.1"
    ports:
    - containerPort: 80
      name:  http

---

apiVersion: v1
kind: Service
metadata:
  name: members-service
spec:
  selector:
    app: members-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
