apiVersion: v1
kind: Pod
metadata:
  name: "members-service"
  namespace: default
  labels:
    app: members-service
spec:
  containers:
    - name: members-service
      image: "pusti/rso2324-team22-members-service:latest"
      ports:
      - containerPort: 80
        name:  http
      env:
        - name: POSTGRES_SERVER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres_server
        - name: POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres_members_database
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres_username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres_password

---

apiVersion: v1
kind: Service
metadata:
  name: members-service
spec:
  type: LoadBalancer
  selector:
    app: members-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
